---
title: "Shotspotter_DC"
author: "Jennifer Li and Sabrina Chok"
date: "4/18/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# loading libraries
library(tidyverse)
library(tigris)
library(sf)
library(gganimate)
library(ggthemes)
library(transformr)
library(viridis)

# pulls the shape file of DC 

shp = places("dc", class = "sf")

# reads in the DC Shotspotter dataset

dc <- read_csv("http://justicetechlab.org/wp-content/uploads/2018/05/washington_dc_2006to2017.csv",
               
               # learned in class (and on Piazza) that the following is a key chunk of code. col_types allows us to pass in any arguments that we want to the read_csv function and overrides the default choices
               
               col_types = cols(
                 incidentid = col_double(),
                 latitude = col_double(),
                 longitude = col_double(),
                 year = col_double(),
                 month = col_double(),
                 day = col_double(),
                 hour = col_double(),
                 minute = col_double(),
                 second = col_double(),
                 numshots = col_double(),
                 type = col_logical()
               ))

# stores the DC Shotspotter dataset as a new object, dc_sample, so we can call it for future use

dc_sample <- dc %>%
  
  # takes a random sample of 200. Original dataset had many observations, which would have taken a while to run.
  
  sample_n(200)

```

```{r map, echo = FALSE, cache = TRUE}
# turns the rows into a sf object using st_as_sf and stores it as dc_locations for future use

dc_locations <- st_as_sf(dc_sample,
                         
                         # lets R know that these are spatial points

                         coords = c("longitude", "latitude"),
                         
                         # creates the coordinate map/sets the coordinate reference system

                         crs = 4326)

# creates the mapping environment using the shp data directly

ggplot(data = shp) +
  
  # plots the shapes data

  geom_sf() +
  
  # plots the points-shaped data (dc_locations), as specified above. Changed the aesthetics to make our data better to visualize!
  
  geom_sf(data = dc_locations, aes(size = numshots, fill = numshots, color = numshots)) +
  
  # we always need to label our graph! this adds a title, so that the reader understands what they are looking at 
  
  labs(title = "Gunfire Incidents in DC between 2006 and 2017",
       
       # adds the subtitle, so the reader understands what years the data is from. Using {} allows variable year to change. The round function rounds each year and drops the decimals that would otherwise be shown.
       
       subtitle = "Year: {round(frame_time)}", 
       
       # # adding a caption allows us to add the source of the data the graph uses
       
       caption = "Source: ShotSpotter Data from the Justice Tech Lab. Thanks for providing the data!") +

  # allows us to have a clean theme that is useful for displaying maps
  
  theme_map() +
  
  # added the fivethirtyeight theme that we enjoy.
  
  theme_fivethirtyeight(base_size = 5) +
  
  scale_size( guide = "none") +
  
  # scale_fill_gradient2(midpoint = 0, mid = "white", high = "red", low = "green") +
  
  # changes the size of the title, so that it fits the map!
  
  # gganimated the graph to progressively show the gunfire incidents by year
  
  transition_time(year)
```

